query GetCurrentSeasonAnime($season: MediaSeason, $seasonYear: Int, $page: Int, $perPage: Int, $isAdult: Boolean) {
    Page(page: $page, perPage: $perPage) {
        media(type: ANIME, season: $season, seasonYear: $seasonYear, sort: POPULARITY_DESC, isAdult: $isAdult) {
            id
            title {
                romaji
                english
                native
            }
            coverImage {
                extraLarge
                large
                medium
                color
            }
            averageScore
            format
            status
            episodes
            genres
            isAdult
        }
    }
}
