query GetManhwaManga($page: Int, $perPage: Int, $countryOfOrigin: CountryCode, $isAdult: Boolean) {
    Page(page: $page, perPage: $perPage) {
        media(type: MANGA, countryOfOrigin: $countryOfOrigin, sort: POPULARITY_DESC, isAdult: $isAdult) {
            id
            title {
                romaji
                english
                native
            }
            coverImage {
                extraLarge
                large
                medium
                color
            }
            averageScore
            format
            chapters
            volumes
            genres
            countryOfOrigin
            isAdult
        }
    }
}
