query GetRandomAnime($page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
        media(type: ANIME, sort: [POPULARITY_DESC], isAdult: false) {
            id
            title {
                romaji
                english
                native
            }
            coverImage {
                extraLarge
                large
                medium
                color
            }
            averageScore
            format
            status
            episodes
            genres
        }
    }
}
