query SearchAnimeByGenre($genres: [String], $page: Int, $perPage: Int, $sort: [MediaSort], $isAdult: Boolean) {
    Page(page: $page, perPage: $perPage) {
        pageInfo {
            total
            currentPage
            lastPage
            hasNextPage
            perPage
        }
        media(type: ANIME, genre_in: $genres, sort: $sort, isAdult: $isAdult) {
            id
            title {
                romaji
                english
                native
            }
            coverImage {
                extraLarge
                large
                medium
                color
            }
            averageScore
            status
            format
            episodes
            seasonYear
            genres
            isAdult
        }
    }
}
