query SearchManga($search: String!, $page: Int, $perPage: Int, $status: MediaStatus, $format: MediaFormat, $averageScore_greater: Int, $isAdult: Boolean) {
    Page(page: $page, perPage: $perPage) {
        pageInfo {
            total
            currentPage
            lastPage
            hasNextPage
            perPage
        }
        media(type: MANGA, search: $search, status: $status, format: $format, averageScore_greater: $averageScore_greater, isAdult: $isAdult) {
            id
            title {
                romaji
                english
                native
            }
            coverImage {
                extraLarge
                large
                medium
                color
            }
            averageScore
            status
            format
            chapters
            volumes
            startDate {
                year
            }
            genres
            isAdult
        }
    }
}
